ARG BASE_IMAGE
FROM ${BASE_IMAGE}

LABEL maintainer="Allen Lee <allen.lee@asu.edu>"

RUN apt-get update \
  && apt-get install -y gnupg2 wget lsb-release \
  && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
  && wget -q -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
  && apt update \
  && apt install -y postgresql-client python3-dev python3-pip \
  && pip3 install pgcli \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /code/server

COPY ./server/package.json ./server/yarn.lock /code/server/
RUN yarn install

COPY ./shared/package.json ./shared/yarn.lock /code/shared/
RUN cd /code/shared && yarn install

COPY ./server /code/server
COPY ./shared /code/shared

ENV NODE_ENV=development

CMD ["yarn", "start"]
