FROM node:13-buster

LABEL maintainer="Allen Lee <allen.lee@asu.edu>"

RUN apt-get update \
  && apt-get install -y libpq-dev python3-dev python3-pip postgresql-client \
  && pip3 install pgcli \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /code/server

COPY ./server/package.json /code/server
RUN yarn install

COPY ./server /code/server
COPY ./shared /code/shared

ENV NODE_ENV=development

CMD ["/code/server/deploy/dev.sh"]
