services:
  server:
    build:
      context: .
    restart: always
    image: port-of-mars/server:dev
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - ./docker/dump:/dump
      - ./docker/logs:/var/log/port-of-mars
      - ./keys/ormconfig.json:/code/server/ormconfig.json
      - ./keys/.pgpass:/root/.pgpass
      - ./keys:/run/secrets
      - ./scripts:/scripts
      - ./server/.env:/code/server/.env
      - ./.prettierrc:/code/.prettierrc
  redis:
    image: redis:7
    restart: always
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marsmadness -d port_of_mars"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: marsmadness
      POSTGRES_PASSWORD_FILE: /run/secrets/pom_db_password
      POSTGRES_DB: port_of_mars
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./keys/pom_db_password:/run/secrets/pom_db_password:ro
      - ./docker/data:/var/lib/postgresql/data/pgdata
