version: '3'
services:
  server:
    build: server
    restart: always
    image: port-of-mars/server/dev:latest
    volumes:
      - ./server:/code
      - ./shared:/shared
      - /code/node_modules
