
version: '3'
services:
  client:
    build: client
    restart: always
    image: port-of-mars/client/dev:latest
    volumes:
      - ./client:/code/client
      - ./shared:/code/shared
      - /code/client/node_modules
    command: './dev.sh'
    ports:
      - '127.0.0.1:8081:8080'
  db: 
    image: postgres:12
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: marsmadness
      POSTGRES_PASSWORD_FILE: /run/secrets/pom_db_password
      POSTGRES_DB: port_of_mars
    volumes:
      - ./server/deploy/pom_db_password:/run/secrets/pom_db_password
      - data:/var/lib/postgresql/data
  server:
    build:
      dockerfile: server/deploy/Dockerfile.dev
    depends_on:
      - db
    ports:
      - '127.0.0.1:2567:2567'
    volumes:
      - ./server:/code/server
      - ./shared:/code/shared
      - ./server/deploy/.pgpass:/root/.pgpass:ro
      - /code/server/node_modules
volumes:
  data:
    driver: local
