version: '3'
services:
  redis:
    volumes:
      - ./docker/redis:/data
  server:
    build:
      args:
        NODE_ARG: production
    image: port-of-mars/server/prod:latest
    ports:
      - '2567:2567'
