version: '3'
services:
  redis:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./server/deploy/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./docker/redis:/data
  server:
    build:
      args:
        NODE_ARG: production
    image: port-of-mars/server/prod:latest
    ports:
      - '2567:2567'
