FROM node:lts-bookworm

LABEL maintainer="Allen Lee <allen.lee@asu.edu>"

RUN apt-get update \
  && apt install -y gnupg2 wget lsb-release postgresql-client python3-dev python3-pip pgcli \
  && apt-get upgrade -y -o Dpkg::Options::="--force-confold" \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /code/server

COPY ./server/package.json ./server/package-lock.json /code/server/
RUN npm install

COPY ./shared/package.json ./shared/package-lock.json /code/shared/
RUN cd /code/shared && npm install

COPY ./server /code/server
COPY ./shared /code/shared

ENV NODE_ENV=development

CMD ["npm", "run", "start"]
