name: Check Code Style/Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clean install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Check formatting
        # run regardless of whether linting caught errors
        if: ${{ success() || failure() }}
        run: yarn style

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clean install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Check formatting
        # run regardless of whether linting caught errors
        if: ${{ success() || failure() }}
        run: yarn style
